# Generated by Django 4.2 on 2023-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_levent1'),
    ]

    operations = [
        migrations.AddField(
            model_name='levent1',
            name='image',
            field=models.ImageField(default=0, upload_to='picture/'),
        ),
    ]
