# Generated by Django 4.2 on 2023-04-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pnumber_feedback_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levent1',
            name='title',
        ),
        migrations.AddField(
            model_name='levent1',
            name='line1',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='levent1',
            name='line2',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='levent1',
            name='line3',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='levent1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='levent1/'),
        ),
    ]
