# Generated by Django 4.2 on 2023-04-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_levent1_line1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levent1',
            name='line1',
            field=models.CharField(default='levent1', max_length=19),
        ),
    ]
