# Generated by Django 4.2 on 2023-04-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_levent1_line1'),
    ]

    operations = [
        migrations.CreateModel(
            name='levent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='levent2', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='levent2/')),
            ],
        ),
        migrations.CreateModel(
            name='levent3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='levent3', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='levent3/')),
            ],
        ),
        migrations.CreateModel(
            name='levent4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='levent4', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='levent4/')),
            ],
        ),
        migrations.CreateModel(
            name='uevent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='uevent1', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uevent1/')),
            ],
        ),
        migrations.CreateModel(
            name='uevent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='uevent2', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uevent2/')),
            ],
        ),
        migrations.CreateModel(
            name='uevent3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='uevent3', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uevent3/')),
            ],
        ),
        migrations.CreateModel(
            name='uevent4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='uevent4', max_length=19)),
                ('line2', models.CharField(blank=True, max_length=19, null=True)),
                ('line3', models.CharField(blank=True, max_length=19, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uevent4/')),
            ],
        ),
    ]
