# Generated by Django 4.2 on 2023-05-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_myprofile_about_remove_myprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='platinumcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketprice', models.IntegerField(default=1500)),
            ],
        ),
    ]
