# Generated by Django 4.2 on 2023-05-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_platinumcart_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='platinumcart',
            name='stage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='ticketprice',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='ticketqty',
            field=models.IntegerField(default=1),
        ),
    ]
