# Generated by Django 4.2 on 2023-05-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_platinumcart_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='platinumcart',
            name='date',
            field=models.CharField(default='April 5 | 10AM', max_length=500),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='language',
            field=models.CharField(default='Tamil', max_length=500),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='locate',
            field=models.CharField(default='Jawaharlal Nehru Stadium | Chennai', max_length=500),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='rated',
            field=models.CharField(default='U/A Family Friendy', max_length=500),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='title',
            field=models.CharField(default='Rockstar Anirudh Music Festival', max_length=500),
        ),
    ]
