# Generated by Django 4.2 on 2023-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_platinumcart_date_platinumcart_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='General Stage', max_length=500)),
                ('ticketqty', models.IntegerField(default=1)),
                ('ticketprice', models.IntegerField(default=500)),
                ('title', models.CharField(default='Rockstar Anirudh Music Festival', max_length=500)),
                ('language', models.CharField(default='Tamil', max_length=500)),
                ('rated', models.CharField(default='U/A Family Friendy', max_length=500)),
                ('date', models.CharField(default='April 5 | 10AM', max_length=500)),
                ('locate', models.CharField(default='Jawaharlal Nehru Stadium | Chennai', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='goldcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='Gold Stage', max_length=500)),
                ('ticketqty', models.IntegerField(default=1)),
                ('ticketprice', models.IntegerField(default=1000)),
                ('title', models.CharField(default='Rockstar Anirudh Music Festival', max_length=500)),
                ('language', models.CharField(default='Tamil', max_length=500)),
                ('rated', models.CharField(default='U/A Family Friendy', max_length=500)),
                ('date', models.CharField(default='April 5 | 10AM', max_length=500)),
                ('locate', models.CharField(default='Jawaharlal Nehru Stadium | Chennai', max_length=500)),
            ],
        ),
    ]
