# Generated by Django 4.2 on 2023-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_generalcart_goldcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='profileimage',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profilepics/'),
        ),
    ]
