# Generated by Django 4.2 on 2023-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_generalcart_user_goldcart_user_platinumcart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='Invalid Username or Password', max_length=1000)),
            ],
        ),
    ]
