# Generated by Django 4.2 on 2023-05-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcart',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcart',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platinumcart',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
    ]
