# Generated by Django 4.2 on 2023-05-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_generalcart_ispaid_goldcart_ispaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platinumcart',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
